services:
  pg-database:
    image: postgres:16.11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: canisayhi? 
      POSTGRES_DB: promeet 
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  keycloak:
    image: keycloak/keycloak:26.4.6
    command: ["start-dev"]
    depends_on:
      - pg-database
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: pg-database
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: canisayhi?
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: canisayhi?
    ports: 
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  pg_data:
  keycloak_data: